title: First Blog
author: Lidan
email: lidan16122@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my first blog.
  My name is Lidan and I am awesome guy!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
